# Generated by Django 4.2.11 on 2024-06-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
