# Generated by Django 4.2.11 on 2024-06-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default='cars/images/default.png', upload_to='cars/images'),
        ),
    ]
